# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='powder',
        ),
        migrations.AddField(
            model_name='coffee',
            name='powder',
            field=models.ManyToManyField(to='mainapp.Powder'),
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='syrup',
        ),
        migrations.AddField(
            model_name='coffee',
            name='syrup',
            field=models.ManyToManyField(to='mainapp.Syrup'),
        ),
    ]
