# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170602_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='extra_instruction',
            field=models.TextField(blank=True),
        ),
    ]
